[package]
name = "crust"
version = "0.1.0"
authors = ["thrizzle. <thrizzle@terabyteis.me>"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11"}
cached = "0.30.0"
miniserde = "0.1.20"
actix-web = "4.0.0-rc.2"
actix-files = "0.6.0-beta.16"
# [dependencies.actix-web]
# git = "https://github.com/actix/actix-web"
# tag = "web-v4.0.0-rc.2"

# [dependencies.actix-files]
# git = "https://github.com/actix/actix-web"
# tag = "files-v0.6.0-beta.16"

[features]
