[package]
name = "crust"
version = "0.1.0"
authors = ["thrizzle. <thrizzle@terabyteis.me>"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = {version="1.0", features=["derive"]}
http-cache-reqwest = "0.2.1"
reqwest-middleware = "0.1.4"
lazy_static = "1.4.0"
tokio = "1.16.1"
http-cache = "0.4.1"

[dependencies.actix-web]
git = "https://github.com/actix/actix-web"
tag = "web-v4.0.0-rc.2"

[features]
