[package]
name = "crust"
version = "0.1.0"
authors = ["thrizzle. <thrizzle@terabyteis.me>"]

[dependencies]
rocket = "0.4.6"
reqwest = { version = "0.11", features = ["json", "blocking"] }
memoize = "0.2.1"
rocket_contrib = {version = "0.4.10", features = ["json"]}
serde = {version="1.0", features=["derive"]}
lru = "0.6.1"

[features]
