name: Rust

on:
  push:
    branches: [ master, unstable ]
    paths:
    - '**.rs'
    - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:

    runs-on: lukemathwalker/cargo-chef:latest-rust-bullseye

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo chef prepare
